//indexState
export const INDEX_HOME_SCREEN = 'INDEX_HOME_SCREEN';
export const INDEX_STUDENT_SCREEN = 'INDEX_STUDENT_SCREEN';
export const INDEX_STUDENTID_SCREEN = 'INDEX_STUDENTID_SCREEN';
export const INDEX_LECTURER_SCREEN = 'INDEX_LECTURER_SCREEN';
export const INDEX_HOMESTUDENT_SCREEN = 'INDEX_HOMESTUDENT_SCREEN';
export const INDEX_STUDENTEXAM_SCREEN = 'INDEX_STUDENTEXAM_SCREEN';